# Generated by Django 5.0.4 on 2024-05-04 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitUser',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
                ('goal', models.CharField(choices=[('Gain Muscle', 'Gain Muscle'), ('Lose Fat', 'Lose Fat'), ('Fitness', 'Fitness')], max_length=15)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('phone', models.CharField(blank=True, max_length=12)),
            ],
        ),
    ]
