# Generated by Django 5.0.4 on 2024-05-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fituser',
            name='name',
        ),
        migrations.AddField(
            model_name='fituser',
            name='fname',
            field=models.CharField(default='John', max_length=20),
        ),
        migrations.AddField(
            model_name='fituser',
            name='lname',
            field=models.CharField(default='Doe', max_length=20),
        ),
    ]
