# Generated by Django 5.0.4 on 2024-05-04 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_remove_fituser_name_fituser_fname_fituser_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fituser',
            name='height',
        ),
        migrations.AddField(
            model_name='fituser',
            name='heightfeet',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(2)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fituser',
            name='heightinch',
            field=models.IntegerField(default=-1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
