# Generated by Django 5.0.4 on 2024-05-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_remove_fituser_height_fituser_heightfeet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fituser',
            name='phone',
        ),
        migrations.AlterField(
            model_name='fituser',
            name='goal',
            field=models.CharField(max_length=15),
        ),
    ]
