# Generated by Django 5.0.6 on 2024-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_shop_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_item',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
