# Generated by Django 5.0.6 on 2024-05-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_shop_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_item',
            name='imr_src',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
