# Generated by Django 5.0.4 on 2024-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_orderdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='fituser',
            name='username',
            field=models.CharField(default='abc', max_length=30),
        ),
    ]
