# Generated by Django 5.0.4 on 2024-05-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_fituser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fituser',
            name='goal',
            field=models.TextField(max_length=15),
        ),
    ]
