# Generated by Django 5.0.4 on 2024-05-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0015_alter_cart_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_ids',
            field=models.ManyToManyField(blank=True, related_name='order_items', to='fitness.shop_item'),
        ),
    ]
