# Generated by Django 5.0.4 on 2024-05-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0016_remove_cart_product_id_cart_product_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user_id',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='fituser',
            name='cart_items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='fitness.cart'),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_ids',
        ),
        migrations.AddField(
            model_name='cart',
            name='product_ids',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='fitness.shop_item'),
        ),
    ]
