# Generated by Django 5.0.4 on 2024-05-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_remove_cart_user_id_cart_quantity_fituser_cart_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_ids',
            new_name='product_id',
        ),
    ]
