# Generated by Django 5.0.4 on 2024-05-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_rename_product_ids_cart_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fituser',
            name='cart_items',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='fitness.cart'),
        ),
    ]
