# Generated by Django 5.0.4 on 2024-05-11 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_alter_fituser_cart_items'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='fituser',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(db_column='product_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='fitness.shop_item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
