# Generated by Django 5.0.4 on 2024-05-11 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0020_remove_cart_product_id_remove_fituser_cart_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.shop_item'),
        ),
    ]
