# Generated by Django 5.0.4 on 2024-05-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0023_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='productname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
