# Generated by Django 5.0.4 on 2024-05-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0024_remove_cart_product_cart_productname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='productname',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
