# Generated by Django 5.0.4 on 2024-05-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0025_remove_cart_productname_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='productname',
            field=models.CharField(default='DUMB', max_length=30),
            preserve_default=False,
        ),
    ]
